//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.15 at 02:03:00 PM CET 
//


package jaxb_classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataset_definitionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataset_definitionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataset_definition" type="{}dataset_definitionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataset_definitionsType", propOrder = {
    "datasetDefinition"
})
public class DatasetDefinitionsType {

    @XmlElement(name = "dataset_definition", required = true)
    protected DatasetDefinitionType datasetDefinition;

    /**
     * Gets the value of the datasetDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link DatasetDefinitionType }
     *     
     */
    public DatasetDefinitionType getDatasetDefinition() {
        return datasetDefinition;
    }

    /**
     * Sets the value of the datasetDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatasetDefinitionType }
     *     
     */
    public void setDatasetDefinition(DatasetDefinitionType value) {
        this.datasetDefinition = value;
    }

}
