//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.23 at 01:38:17 PM CET 
//


package jaxb_classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataset_definitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataset_definitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{}textType"/>
 *         &lt;element name="name" type="{}textType"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="distribution" type="{}textType"/>
 *         &lt;element name="minimum" type="{}textType"/>
 *         &lt;element name="maximum" type="{}textType"/>
 *         &lt;element name="decimals" type="{}textType"/>
 *         &lt;element name="itemcount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataset_items" type="{}dataset_itemsType"/>
 *         &lt;element name="number_of_items" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataset_definitionType", propOrder = {
    "status",
    "name",
    "type",
    "distribution",
    "minimum",
    "maximum",
    "decimals",
    "itemcount",
    "datasetItems",
    "numberOfItems"
})
public class DatasetDefinitionType {

    @XmlElement(required = true)
    protected TextType status;
    @XmlElement(required = true)
    protected TextType name;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected TextType distribution;
    @XmlElement(required = true)
    protected TextType minimum;
    @XmlElement(required = true)
    protected TextType maximum;
    @XmlElement(required = true)
    protected TextType decimals;
    @XmlElement(required = true)
    protected String itemcount;
    @XmlElement(name = "dataset_items", required = true)
    protected DatasetItemsType datasetItems;
    @XmlElement(name = "number_of_items", required = true)
    protected String numberOfItems;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setStatus(TextType value) {
        this.status = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setName(TextType value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the distribution property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getDistribution() {
        return distribution;
    }

    /**
     * Sets the value of the distribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setDistribution(TextType value) {
        this.distribution = value;
    }

    /**
     * Gets the value of the minimum property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getMinimum() {
        return minimum;
    }

    /**
     * Sets the value of the minimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setMinimum(TextType value) {
        this.minimum = value;
    }

    /**
     * Gets the value of the maximum property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getMaximum() {
        return maximum;
    }

    /**
     * Sets the value of the maximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setMaximum(TextType value) {
        this.maximum = value;
    }

    /**
     * Gets the value of the decimals property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getDecimals() {
        return decimals;
    }

    /**
     * Sets the value of the decimals property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setDecimals(TextType value) {
        this.decimals = value;
    }

    /**
     * Gets the value of the itemcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemcount() {
        return itemcount;
    }

    /**
     * Sets the value of the itemcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemcount(String value) {
        this.itemcount = value;
    }

    /**
     * Gets the value of the datasetItems property.
     * 
     * @return
     *     possible object is
     *     {@link DatasetItemsType }
     *     
     */
    public DatasetItemsType getDatasetItems() {
        return datasetItems;
    }

    /**
     * Sets the value of the datasetItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatasetItemsType }
     *     
     */
    public void setDatasetItems(DatasetItemsType value) {
        this.datasetItems = value;
    }

    /**
     * Gets the value of the numberOfItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfItems() {
        return numberOfItems;
    }

    /**
     * Sets the value of the numberOfItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfItems(String value) {
        this.numberOfItems = value;
    }

}
