//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.15 at 02:03:00 PM CET 
//


package jaxb_classes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb_classes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb_classes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QuestiontextType }
     * 
     */
    public QuestiontextType createQuestiontextType() {
        return new QuestiontextType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link AnswerType }
     * 
     */
    public AnswerType createAnswerType() {
        return new AnswerType();
    }

    /**
     * Create an instance of {@link UnitsType }
     * 
     */
    public UnitsType createUnitsType() {
        return new UnitsType();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link DatasetDefinitionType }
     * 
     */
    public DatasetDefinitionType createDatasetDefinitionType() {
        return new DatasetDefinitionType();
    }

    /**
     * Create an instance of {@link DatasetItemType }
     * 
     */
    public DatasetItemType createDatasetItemType() {
        return new DatasetItemType();
    }

    /**
     * Create an instance of {@link DatasetItemsType }
     * 
     */
    public DatasetItemsType createDatasetItemsType() {
        return new DatasetItemsType();
    }

    /**
     * Create an instance of {@link Quiz }
     * 
     */
    public Quiz createQuiz() {
        return new Quiz();
    }

    /**
     * Create an instance of {@link Quiz.Question }
     * 
     */
    public Quiz.Question createQuizQuestion() {
        return new Quiz.Question();
    }

    /**
     * Create an instance of {@link SubquestionType }
     * 
     */
    public SubquestionType createSubquestionType() {
        return new SubquestionType();
    }

    /**
     * Create an instance of {@link AnswerType.Feedback }
     * 
     */
    public AnswerType.Feedback createAnswerTypeFeedback() {
        return new AnswerType.Feedback();
    }

    /**
     * Create an instance of {@link DatasetDefinitionsType }
     * 
     */
    public DatasetDefinitionsType createDatasetDefinitionsType() {
        return new DatasetDefinitionsType();
    }

}
