//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.15 at 02:03:00 PM CET 
//


package jaxb_classes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="question" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="category" type="{}textType" minOccurs="0"/>
 *                   &lt;element name="name" type="{}textType" minOccurs="0"/>
 *                   &lt;element name="questiontext" type="{}questiontextType" minOccurs="0"/>
 *                   &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="image_base64" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="generalfeedback" type="{}textType" minOccurs="0"/>
 *                   &lt;element name="defaultgrade" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="penalty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="hidden" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="shuffleanswers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="single" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="usecase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="subquestion" type="{}subquestionType" maxOccurs="unbounded"/>
 *                   &lt;element name="correctfeedback" type="{}textType" minOccurs="0"/>
 *                   &lt;element name="partiallycorrectfeedback" type="{}textType" minOccurs="0"/>
 *                   &lt;element name="incorrectfeedback" type="{}textType" minOccurs="0"/>
 *                   &lt;element name="answernumbering" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="answer" type="{}answerType" maxOccurs="unbounded"/>
 *                   &lt;element name="units" type="{}unitsType" minOccurs="0"/>
 *                   &lt;element name="dataset_definitions" type="{}dataset_definitionsType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "question"
})
@XmlRootElement(name = "quiz")
public class Quiz {

    @XmlElement(required = true)
    protected List<Quiz.Question> question;

    /**
     * Gets the value of the question property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the question property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuestion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Quiz.Question }
     * 
     * 
     */
    public List<Quiz.Question> getQuestion() {
        if (question == null) {
            question = new ArrayList<Quiz.Question>();
        }
        return this.question;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="category" type="{}textType" minOccurs="0"/>
     *         &lt;element name="name" type="{}textType" minOccurs="0"/>
     *         &lt;element name="questiontext" type="{}questiontextType" minOccurs="0"/>
     *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="image_base64" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="generalfeedback" type="{}textType" minOccurs="0"/>
     *         &lt;element name="defaultgrade" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="penalty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="hidden" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="shuffleanswers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="single" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="usecase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="subquestion" type="{}subquestionType" maxOccurs="unbounded"/>
     *         &lt;element name="correctfeedback" type="{}textType" minOccurs="0"/>
     *         &lt;element name="partiallycorrectfeedback" type="{}textType" minOccurs="0"/>
     *         &lt;element name="incorrectfeedback" type="{}textType" minOccurs="0"/>
     *         &lt;element name="answernumbering" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="answer" type="{}answerType" maxOccurs="unbounded"/>
     *         &lt;element name="units" type="{}unitsType" minOccurs="0"/>
     *         &lt;element name="dataset_definitions" type="{}dataset_definitionsType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "category",
        "name",
        "questiontext",
        "image",
        "imageBase64",
        "generalfeedback",
        "defaultgrade",
        "penalty",
        "hidden",
        "shuffleanswers",
        "single",
        "usecase",
        "subquestion",
        "correctfeedback",
        "partiallycorrectfeedback",
        "incorrectfeedback",
        "answernumbering",
        "answer",
        "units",
        "datasetDefinitions"
    })
    public static class Question {

        protected TextType category;
        protected TextType name;
        protected QuestiontextType questiontext;
        protected String image;
        @XmlElement(name = "image_base64")
        protected String imageBase64;
        protected TextType generalfeedback;
        protected String defaultgrade;
        protected String penalty;
        protected String hidden;
        protected String shuffleanswers;
        protected String single;
        protected String usecase;
        @XmlElement(required = true)
        protected List<SubquestionType> subquestion;
        protected TextType correctfeedback;
        protected TextType partiallycorrectfeedback;
        protected TextType incorrectfeedback;
        protected String answernumbering;
        @XmlElement(required = true)
        protected List<AnswerType> answer;
        protected UnitsType units;
        @XmlElement(name = "dataset_definitions")
        protected DatasetDefinitionsType datasetDefinitions;
        @XmlAttribute
        protected String type;

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link TextType }
         *     
         */
        public TextType getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link TextType }
         *     
         */
        public void setCategory(TextType value) {
            this.category = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link TextType }
         *     
         */
        public TextType getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link TextType }
         *     
         */
        public void setName(TextType value) {
            this.name = value;
        }

        /**
         * Gets the value of the questiontext property.
         * 
         * @return
         *     possible object is
         *     {@link QuestiontextType }
         *     
         */
        public QuestiontextType getQuestiontext() {
            return questiontext;
        }

        /**
         * Sets the value of the questiontext property.
         * 
         * @param value
         *     allowed object is
         *     {@link QuestiontextType }
         *     
         */
        public void setQuestiontext(QuestiontextType value) {
            this.questiontext = value;
        }

        /**
         * Gets the value of the image property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImage() {
            return image;
        }

        /**
         * Sets the value of the image property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImage(String value) {
            this.image = value;
        }

        /**
         * Gets the value of the imageBase64 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImageBase64() {
            return imageBase64;
        }

        /**
         * Sets the value of the imageBase64 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImageBase64(String value) {
            this.imageBase64 = value;
        }

        /**
         * Gets the value of the generalfeedback property.
         * 
         * @return
         *     possible object is
         *     {@link TextType }
         *     
         */
        public TextType getGeneralfeedback() {
            return generalfeedback;
        }

        /**
         * Sets the value of the generalfeedback property.
         * 
         * @param value
         *     allowed object is
         *     {@link TextType }
         *     
         */
        public void setGeneralfeedback(TextType value) {
            this.generalfeedback = value;
        }

        /**
         * Gets the value of the defaultgrade property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefaultgrade() {
            return defaultgrade;
        }

        /**
         * Sets the value of the defaultgrade property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefaultgrade(String value) {
            this.defaultgrade = value;
        }

        /**
         * Gets the value of the penalty property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPenalty() {
            return penalty;
        }

        /**
         * Sets the value of the penalty property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPenalty(String value) {
            this.penalty = value;
        }

        /**
         * Gets the value of the hidden property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHidden() {
            return hidden;
        }

        /**
         * Sets the value of the hidden property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHidden(String value) {
            this.hidden = value;
        }

        /**
         * Gets the value of the shuffleanswers property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShuffleanswers() {
            return shuffleanswers;
        }

        /**
         * Sets the value of the shuffleanswers property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShuffleanswers(String value) {
            this.shuffleanswers = value;
        }

        /**
         * Gets the value of the single property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSingle() {
            return single;
        }

        /**
         * Sets the value of the single property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSingle(String value) {
            this.single = value;
        }

        /**
         * Gets the value of the usecase property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsecase() {
            return usecase;
        }

        /**
         * Sets the value of the usecase property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsecase(String value) {
            this.usecase = value;
        }

        /**
         * Gets the value of the subquestion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the subquestion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubquestion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SubquestionType }
         * 
         * 
         */
        public List<SubquestionType> getSubquestion() {
            if (subquestion == null) {
                subquestion = new ArrayList<SubquestionType>();
            }
            return this.subquestion;
        }

        /**
         * Gets the value of the correctfeedback property.
         * 
         * @return
         *     possible object is
         *     {@link TextType }
         *     
         */
        public TextType getCorrectfeedback() {
            return correctfeedback;
        }

        /**
         * Sets the value of the correctfeedback property.
         * 
         * @param value
         *     allowed object is
         *     {@link TextType }
         *     
         */
        public void setCorrectfeedback(TextType value) {
            this.correctfeedback = value;
        }

        /**
         * Gets the value of the partiallycorrectfeedback property.
         * 
         * @return
         *     possible object is
         *     {@link TextType }
         *     
         */
        public TextType getPartiallycorrectfeedback() {
            return partiallycorrectfeedback;
        }

        /**
         * Sets the value of the partiallycorrectfeedback property.
         * 
         * @param value
         *     allowed object is
         *     {@link TextType }
         *     
         */
        public void setPartiallycorrectfeedback(TextType value) {
            this.partiallycorrectfeedback = value;
        }

        /**
         * Gets the value of the incorrectfeedback property.
         * 
         * @return
         *     possible object is
         *     {@link TextType }
         *     
         */
        public TextType getIncorrectfeedback() {
            return incorrectfeedback;
        }

        /**
         * Sets the value of the incorrectfeedback property.
         * 
         * @param value
         *     allowed object is
         *     {@link TextType }
         *     
         */
        public void setIncorrectfeedback(TextType value) {
            this.incorrectfeedback = value;
        }

        /**
         * Gets the value of the answernumbering property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAnswernumbering() {
            return answernumbering;
        }

        /**
         * Sets the value of the answernumbering property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAnswernumbering(String value) {
            this.answernumbering = value;
        }

        /**
         * Gets the value of the answer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the answer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAnswer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AnswerType }
         * 
         * 
         */
        public List<AnswerType> getAnswer() {
            if (answer == null) {
                answer = new ArrayList<AnswerType>();
            }
            return this.answer;
        }

        /**
         * Gets the value of the units property.
         * 
         * @return
         *     possible object is
         *     {@link UnitsType }
         *     
         */
        public UnitsType getUnits() {
            return units;
        }

        /**
         * Sets the value of the units property.
         * 
         * @param value
         *     allowed object is
         *     {@link UnitsType }
         *     
         */
        public void setUnits(UnitsType value) {
            this.units = value;
        }

        /**
         * Gets the value of the datasetDefinitions property.
         * 
         * @return
         *     possible object is
         *     {@link DatasetDefinitionsType }
         *     
         */
        public DatasetDefinitionsType getDatasetDefinitions() {
            return datasetDefinitions;
        }

        /**
         * Sets the value of the datasetDefinitions property.
         * 
         * @param value
         *     allowed object is
         *     {@link DatasetDefinitionsType }
         *     
         */
        public void setDatasetDefinitions(DatasetDefinitionsType value) {
            this.datasetDefinitions = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
